<?php

/**
 * Implements hook_preprocess_page().
 * Replaces hook_init().
 */
function tipsy_preprocess_page(&$variables)
{
  backdrop_add_library('tipsy', 'tipsy', TRUE);
	backdrop_add_js(backdrop_get_path('module', 'tipsy').'/javascripts/tipsy.js');
	backdrop_add_js(backdrop_get_path('module', 'tipsy').'/javascripts/tipsy.admin.js');
}

/**
 * Implements hook_library_info().
 * Replaces hook_library().
 */
function tipsy_library_info() {
	$path = libraries_get_path('tipsy');
  $libraries['tipsy'] = array(
    'title' => 'Tipsy',
    'website' => 'http://onehackoranother.com/projects/jquery/tipsy/',
    'version' => '0.1.7',
    'js' => array(
      $path . '/jquery.tipsy.js' => array(),
    ),
    'css' => array(
      $path . '/tipsy.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );

  $settings = _tipsy_get_settings();
  if ($settings['backdrop_forms']['forms'] == 0) {
    unset($settings['backdrop_forms']);
  }
  backdrop_add_js(array('tipsy' => $settings), 'setting');

  return $libraries;
}

/**
 * Implements hook_menu().
 */
function tipsy_menu()
{
  $items = array();

  $items['admin/config/content/tipsy'] = array(
    'title' => 'Tipsy',
    'description' => 'Integrates tipsy tooltips with Backdrop',
    'page callback' => 'backdrop_get_form',
    'access callback' => 'user_access',
    'access arguments' => array('administer tipsy'),
    'page arguments' => array('tipsy_admin'),
    'file' => 'tipsy.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_perm().
 */
function tipsy_permission()
{
  $permissions = array();

  $permissions['administer tipsy'] = array(
    'title' => t('Administer Tipsy'),
    'description' => t('Allows users to configure Tipsy.'),
  );

  return $permissions;
}

/**
 * Implements hook_theme().
 */
function tipsy_theme()
{
  return array(
    'tipsy_custom_selectors_form' => array(
      'render element' => 'form',
      'file' => 'tipsy.admin.inc',
    ),
  );
}

/**
 * Helper function to retrieve all settings for tipsy.
 */
function _tipsy_get_settings()
{
  $settings = config_get('tipsy.settings');
  return $settings;
}

/**
 * Implements hook_config_info().
 */
function tipsy_config_info()
{
  $prefixes['tipsy.settings'] = array(
    'label' => t('Tipsy'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}